export const FETCH_PRODUCTS_KR = "FETCH_PRODUCTS_KR";
export const ADD_NEW_PRODUCT_KR = "ADD_NEW_PRODUCT_KR";
export const EDIT_PRODUCT_KR = "EDIT_PRODUCT_KR";
export const DELETE_PRODUCT_KR = "DELETE_PRODUCT_KR";

export const FETCH_PRODUCTS_VK = "FETCH_PRODUCTS_VK";
export const ADD_NEW_PRODUCT_VK = "ADD_NEW_PRODUCT_VK";
export const EDIT_PRODUCT_VK = "EDIT_PRODUCT_VK";
export const DELETE_PRODUCT_VK = "DELETE_PRODUCT_VK";

export const LOADING_SET = "LOADING_SET";

//FOR TOKEN ADD  AND REMOVE
export const TOKEN_SET = "TOKEN_SET";
export const TOKEN_REMOVE = "TOKEN_REMOVE ";

//FOR ERROR AND SUCCESS NOTIFICATION
export const ERROR_MESSAGE = "ERROR_MESSAGE";
export const SUCCESS_MESSAGE = "SUCCESS_MESSAGE";
export const CLEAR_ERROR = "CLEAR_ERROR";
export const CLEAR_SUCCESS = "CLEAR_SUCCESS";

//FOR LOGIN AND LOGOUT
export const USER_LOGIN = "USER_LOGIN";
export const USER_LOGOUT = "USER_LOGOUT";

//FOR ERROR IN AUTH PROCESS
export const RESPONSE_SUCCESS = "RESPONSE_SUCCESS";
export const RESPONSE_ERROR = "RESPONSE_ERROR";
export const RESPONSE_CLEAR = "RESPONSE_CLEAR";

export const CREATE_SESSION = "CREATE_SESSION";
export const DESTROY_SESSION = "DESTROY_SESSION";

//FOR FETCHING AND REMOVING USER
export const FETCH_USER = "FETCH_USER";
export const REMOVE_USER = "REMOVE_USER";
export const UPDATE_USER_PROFILE = "UPDATE_USER_PROFILE";

// AUXILLARY ACTION TYPES
export const SET_CURR_KR_PRODUCT_VIEW = "SET_CURR_KR_PRODUCT_VIEW";
// export const SET_CURR_VK_PRODUCT_VIEW = "SET_CURR_VK_PRODUCT_VIEW";

export const SET_DROPDOWN_SHOW = "SET_DROPDOWN_SHOW";

export const SET_ENQUIRY_RESPONSE = "SET_ENQUIRY_RESPONSE";
